### ISSUE TITLE
 Minimal working example for largely _automated_ import, use & render of software citation?

### ISSUE THREAD

**Issue by katrinleinweber** [force11/force11-sciwg#48]
Hello!

I read through https://research-software.org/citation/researchers/ and was left wondering whether there are already technical solutions to the three workflow steps of importing, using-in-a-manuscript and rendering a software citation? A beginner-friendly [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) so to speak, that does not rely on formatting a reference list manually, or [fiddling with BibTeX item types](https://tex.stackexchange.com/questions/175776/how-can-i-create-entirely-new-data-types-with-biblatex-biber) or writing one's own CSL?

Importing works already well, if a BibTeX snippet is offered or a Zotero-translator. Example: [R-Packages.js](https://github.com/zotero/translators/commits/master/R-Packages.js) on [CRAN](https://cran.r-project.org/web/packages/knitr/index.html).

Using is also fine, since [many](https://github.com/mangecoeur/Citer) [text](https://duckduckgo.com/lite?q=atom+package+bibtex) editors and word processors can integrate well with most reference managers. Thus, inserting a citation into the doc works also fine.

However, when one actually wants to render the document, which BibTeX or CSL styles and processors are available that treat software in a minimally useful way? Such as rendering the version number from it's own field instead of a `v1.2.3` appendix in the title or description?

**Comment by sdruskat** [comment]
> whether there are already technical solutions to the three workflow steps of importing, using-in-a-manuscript and rendering a software citation?

From the CFF perspective, not yet. There's ongoing work around CITATION.cff file readers in different languages ([Java](https://github.com/citation-file-format/cff-reader-java), [Ruby](https://github.com/citation-file-format/ruby-cff), [Python](https://github.com/citation-file-format/citationcff)) which will be helpful to interface with other workflow components (generators, converters, etc.). 

Social gaps here include getting vendors to use the tools we create.

Technical gaps include that BibTeX is broken for software citations, which can be circumvented, e.g., by reading the version field from metadata into the title field as `Title (Version {version})`. Also on the publishers' side, the relevant metadata formats (JACS I think?) need to be adapted to accommodate the relevant metadata.

Working towards that MVE one step at a time.

**Comment by katrinleinweber** [comment]
One step forward on the import side: https://github.com/zotero/translators/pull/1578 :-)

**Comment by katrinleinweber** [comment]
> Technical gaps include that BibTeX is broken for software citations [...] 

True ([as explained](https://figshare.com/articles/Track_2_Lightning_Talk_Should_CITATION_files_be_standardized_/3827058)), but what is preventing this "unsupported types" from becoming supported by Bib(La)Tex/biber? There seem to be [no feature](https://github.com/plk/biblatex/issues?q=software) [requests there](https://github.com/plk/biber/issues/?q=software). However, thanks to [doi:10.5446/35357](https://doi.org/10.5446/35357#t=18:34,18:55) we seem to be close to putting together the necessary files. 

Dear @moewew, do you know whether there is a reason why `@software` is not yet supported in Bib(La)TeX/biber? Not simply due to a lack of PRs, I hope ;-)

**Comment by moewew** [comment]
`@software` is among the known entry types, but it is not supported by the standard styles at the moment. That means in most cases `@software` falls back to `@misc`, which seems good enough for me (see https://tex.stackexchange.com/q/254610/). There are some custom styles that implement support for `@software`, though. The wonderful https://github.com/alex-ball/biblatex-oxref comes to mind, the no less wonderful https://github.com/plk/biblatex-apa also supports `@software`.

I can't tell you why exactly this particular entry type is not amongst the supported types. But I assume it was not thought of as important enough when the package was written by its original author. The current stance toward support for unsupported entry types seems to be that there needs to be an interesting challenge to meet to warrant inclusion into the core. See this response to a feature request for `@standard` https://github.com/plk/biblatex/issues/388.

I tend to be (too) conservative when it comes to these kind of requests since I worry about feature creep.

If you are not satisfies with the status quo that the mapping to `@misc` gives you in the standard styles, head over to https://github.com/plk/biblatex/issues to discuss this. There is quite a lot to supporting a new entry type and quite some things would have to be discussed and decided upon if the entry type is deemed worthy for support.

**Comment by danielskatz** [comment]
I think this would be great to do, and fits this group's goals quite well, if someone wants to take it on.  It's been a potential action for a long time.

**Comment by katrinleinweber** [comment]
Ah-ha, thank you! If more several PRs would add support for `@software` to important styles, would that be a way to increase chances to get the type itself supported officially? The "encountered often" argument looks well covered by [research](http://rse.ac.uk/community/research-software-groups-rsgs/) software [engineers](https://www.force11.org/group/software-citation-implementation-working-group). I'm not sure about the `and require changes to internals`, though.

If support can be increased with "existing biber-only features", I see the question of how to get such patches onto peoples machines and into production workflows arise. Which I hope will be less relevant after official support.

**Comment by moewew** [comment]
> If several PRs with support for `@software` were to appear against important styles, would that be a way to increase chances to get the type itself supported officially?

Just so I understand you correctly: What would "official support" mean for you? `@software` is already a recognised entry type in `biblatex`'s standard model and it is even acknowledged in the documentation. Its being an "unsupported type" only means that there is no specific driver set up in the `.bbx` file and that it uses the one defined for `@misc`. Even at the moment `@software` is a perfectly valid entry type that gives (I think) fairly satisfying output even with the standard styles.

So maybe we have a problem terminology here. `@sofware` is officially supported in that it is a recognised and known entry type. It's just that `biblatex` has nothing special set up for it and treats it as `@misc`, that is what "unsupported" means in the *Unsupported Types* section heading.

`@software` is as valid an entry type as `@book`. A properly unsupported entry type would be `@flobbel`.

**Comment by katrinleinweber** [comment]
Thanks for explaining :-) My apologies! Yes, I meant a specific driver, so that a [useful set of fields](https://github.com/force11/force11-sciwg/issues/5) (and their formatting also, I presume) can be defined to implement (at least an MVE of) the [Software Citation Principles](https://peerj.com/articles/cs-86/).

**Comment by moewew** [comment]
Maybe we should head over to the `biblatex` bug tracker with a proper list of what you want, what you can have so far and what would need to be done on the `biblatex` side.

At the moment I'm sceptical that a lot would have to be done. Even without a dedicated driver `@software` can use type-specific formatting (since it is a valid entry type). And I think even without any modifications almost all columns of https://doi.org/10.7717/peerj.2394/table-2 are covered. 

- [x] `biblatex` offers support for `doi`s out of the box for all entry types, so that could cover "unique identifiers", but there is also the customisable `eprint` field.
- [x] software name could go to the `title` field
- [x] authors go in the `author` field. The field accepts "real names" as well as pseudonyms or names of collaborations or corporations (use double curly braces for corporate authors)
- [x] Contributor role could go to the `authortype` field. For several roles `editor`, `editora` to `editorc` and the corresponding `editor...type` fields are available
- [x] version number goes into the `version` field
- [x] release date goes into the `date` field
- [x] location/repository could go into `url`
- [ ] indexed citations: not sure what exactly that is and if it is applicable here
- [ ] software license: we don't have a field for that.
- [x] description: maybe `abstract`?

**Comment by danielskatz** [comment]
Just to add another topic to this discussion, I think an additional step would be to work with groups that create the documents that are used by authors to create their publications, including class files and templates.

**Comment by katrinleinweber** [comment]
Just to clarify:

> `@misc` also supports a `type` field that could be filled with the keyword `software`.

primarily means [`type = {software}`, correct? This is used often](https://github.com/search?o=desc&q=misc+keywords+%22type%3Asoftware%22+extension%3Abib&s=indexed&type=Code), but I also saw the notation `keywords={type:...}` for other... Well, types.

**Comment by katrinleinweber** [comment]
> biblatex 3.12 has … `@software` and friends … absolutely fine, the standard styles just don't have a dedicated driver set up for these types … https://github.com/plk/biblatex/issues/753#issuecomment-436159332

**Comment by sdruskat** [comment]
I think a good example of a largely automated workflow of importing, using and rendering software citation is the Netherlands eScience Center's Research Software Directory (https://research-software.nl/):

(From Spaaks, Jurriaan H.; Maassen, Jason; Klaver, Tom; Verhoeven, Stefan (2018): How the Netherlands eScience Center uses CFF to promote software citation. figshare. Presentation at CFF Hack Day. https://doi.org/10.6084/m9.figshare.7053608.v1)

1. code is on GitHub
2. GitHub-Zenodo integration to mint DOIs whenever a release is made.
3. Research Software Directory has an Admin interface, provides concept DOI
4. scraper asks Zenodo for the associated versioned DOIs
5. scraper then visits the links for each, 
    - looks for a `CITATION.cff`
    - checks if it's valid
    - generates BibTeX, EndNote, RIS
    - generates CodeMeta that is embedded in the landing page for a software

**Comment by katrinleinweber** [comment]
I think we can do better then 5+X steps.

What if @Zenodo started providing BibTeX with `@software`? Think it's time to revisit https://github.com/zenodo/zenodo/issues/1428 and convince the important downstream tools who hiccup on `@software` to behave more gracefully.

Also, is there any BibTeX style that already support `@software`? If yes, we'd be at:

> 1. code is on GitHub
> 2. GitHub-Zenodo integration to mint DOIs whenever a release is made.

3. copy BibTeX from Zenodo to a project- or user-specific `.bib`

Implicitly, both my & probably @sdruskat's list continue with:

- insert software item into document (`.md`, `.tex`, etc.)
- compile with pandoc, latex, etc.

**Comment by moewew** [comment]
I'm not sure if it is sufficiently clear, so apologies if I state the obvious.

The world of `.bib` files is extremely fragmented. There is not only the obvious dichotomy BibTeX vs `biblatex` that most people and tools are aware of in one way or another. All BibTeX styles are allowed to have potentially different data models and you would have to change all `.bst` styles available today that don't support `@software` to reach 100% coverage.

For anything other than a core set of fields listed in §3 of BibTeXing by Oren Patashnik (["`btxdoc`"](http://mirrors.ctan.org/biblio/bibtex/base/btxdoc.pdf)), that was finalised in the late eighties, consensus among `.bst` files (BibTeX styles) can not be guaranteed. The *base* styles have remained largely unchanged since 1988 and don't even support popular things like a `url` field or DOIs or even an `@online` or `@electronic` entry type. Other styles have bridged that gap and added these fields (and others) to their repertoire. But not all styles have done that in the same way, so that inconsistencies and incompatibilities between styles have to be expected. BibTeX files are completely self-contained with regards to which fields and types they support, so every `.bst` file would have to be changed separately.

Most BibTeX styles will not know a `@software` type. If `@software` is used regardless, BibTeX will throw an error and a fallback definition is used that will probably still give acceptable output (compared to what the style can provide overall). The overall chances of affecting large scale changes to many `.bst` files are slim, many styles have been stable for years and could be seen as abandoned. In some cases it might be possible for other people to take over maintenance of styles (the LPPL allows this), but I'm not sure how well this would be received. As far as I am aware there was no large-scale surge to action to add URL/DOI support to all sorts of established styles, and that is something about which people would probably be much more excited than `@software`. People found ways around it like `howpublished = {\url{http://example.com} access date 07/11/2018}`, `urlbst` or different styles - and that was that.

`biblatex` entered the scene much later and could profit from the experience with BibTeX to start from a more mature and rich data model. It is an express feature of `biblatex` that styles and users are allowed to change the data model (i.e. to add or remove field or entry types), but the assumption has been that most well-written styles only extend the data model and do not throw out fields and types. Overall the data model is fairly homogeneous because many things were included in the standard data model that were found lacking in BibTeX, but if we are talking about even more specialised stuff like legal citations, you will find that there is again fragmentation among the styles that provide such features.

Since `@software` has been a valid entry type for `biblatex` from as far back as I could trace it (v0.8e lists it, the wording is a bit confusing, but it should have been treated like it is treated now), I would venture a guess that most `biblatex` styles support `@software` at least in so far that something useful comes out and there is no warning.

----

When you are now trying to convince data providers or exporters to use `@software` instead of `@misc`, you are fighting a similar battle that people would fight to have those exporters export
```
url     = {http://example.com},
urldate = {2018-11-07},
```
instead of
```
howpublished = {\url{http://example.com}, 07/11/2018},
```
The latter is quite universal, but the former is clearly preferable for styles that support it. Many exporters go for the lowest common denominator because that causes the fewest complaints about incorrect or missing data. But with that approach many tools that would be able to offer more can't be used to their full potential.

I for one have resigned myself to the fact that data providers often produce `.bib` files that are far from perfect and far from best practice for the tools I use. See also [Software-generated bibliographic entries: common errors and other mistakes to check before use](https://tex.stackexchange.com/q/386053/35864) on TeX.SX. The `@misc`/`@software` quibble is just another issues on that list.

**Comment by katrinleinweber** [comment]
Thanks to @dbouquin et al. we have [a template with explanation](https://github.com/force11/force11-sciwg/blame/46ab9dc9a5e89ab799127270a709c55c2603fa23/meetings/20190702-Notes.md#L93-L94) now :-)

**Comment by katrinleinweber** [comment]
[Zenodo now generates BibTeX with `@software`](https://github.com/zenodo/zenodo/pull/1872) where appropriate. cc @moewew
