### ISSUE TITLE
"published" language

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-sciwg#66]
Based on discussion in Section 2 of [A&P google doc](https://docs.google.com/document/d/1ze2Bh0pZXCy7_bHcC7CumQRmBAv8qP6reao4yU4JToY/edit?ts=5bb29c86#)

* In the software citation principles paper, we used "published" to mean than an author had submitted the software to an archival repository along with metadata, and that the repository had issued an identifier.  There is some confusion about this term.  Is there a better term?
* We also need to make clear that made public is not the same as "published"

**Comment by moranegg** [comment]
"Published software" should be equivalent to "published article" in the research domain.
An article that is public but not published does not have the same stature than one published with a complete set of metadata and which will result with a standard citation.

That's why software made available online, in my opinion, is not "published software", but it doesn't mean it  shouldn't be cited. 

I would reserve the term published software to software that was published by a journal or software that was deposited in an archive (like [Zenodo](https://zenodo.org/), [HAL](hal.archives-ouvertes.fr), etc.).

**Comment by danielskatz** [comment]
I think this has been resolved in the document, and I'm closing this issue to avoid having duplicate discussions in 2 places - if you think this is still a problem in the document, please add a comment or make a suggestion there.
