### ISSUE TITLE
Software Heritage and software identification

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-sciwg#70]
Based on discussion in Section 3.1 and 3.5 of [A&P google doc](https://docs.google.com/document/d/1ze2Bh0pZXCy7_bHcC7CumQRmBAv8qP6reao4yU4JToY/edit?ts=5bb29c86#)

* In 3.1.4, there is an example of identification of software in software heritage: https://archive.softwareheritage.org/swh:1:rev:81c66c0db5c381dacc0841a4c16e0b3876b15b89;origin=https://github.com/applicationskeleton/Skeleton/
* In a comment, another way to identify this same software is https://identifiers.org/swh:1:rev:81c66c0db5c381dacc0841a4c16e0b3876b15b89
* Which, if either, should we recommend?

**Comment by moranegg** [comment]
I would recommend the first one as the by default url for the swh-id and add it is possible to resolve the identifier with different resolvers (which is also possible with N2t).

I believe that the comment was about the usage of an identifier instead of a url.

So I will distinguish between the swh-id  -`swh:1:rev:81c66c0db5c381dacc0841a4c16e0b3876b15b89;origin=https://github.com/applicationskeleton/Skeleton/`
 and the permalinks available with different resolvers

**Comment by danielskatz** [comment]
I think we've moved this discussion into the document, and perhaps finished it there, so I'm going to close this issue
